#! /bin/zsh

function usage {
    echo ""
    echo "Toolkit search"
    echo ""
    echo "By default the tool will copy the contents of the selected file to your clipboard"
    echo ""
    echo "usage: toolkit"
    echo ""
    echo "Options"
    echo "  --edit                  will open the file in vscode to edit"
    echo "  -e"
    echo ""
}

while [ $# -gt 0 ]; do
    if [[ $1 == "-h" || $1 == "--help" ]]; then
      usage;
      exit 0
    fi

    if [[ $1 == "-e" || $1 == "--edit" ]]; then
      shift
      cd '"$TOOLKIT_PATH"'
      fzf | xargs -r  /usr/local/bin/code $1
      exit 0
    fi
done

source ~/.zshrc

cd $TOOLKIT_PATH

if which tmux >/dev/null;
then
  language=$(find . -maxdepth 1 -mindepth 1 -type d -print | fzf-tmux -p)
else
  language=$(find . -maxdepth 1 -mindepth 1 -type d -print | fzf)
fi

if [[ -z "$language" ]]; 
then 
  exit 0
fi

cd $language


if which tmux >/dev/null;
then
  selected=$(find * -type f -name '*' | fzf-tmux -p)
else
  selected=$(find * -type f -name '*' | fzf)
fi

if [[ -z "$selected" ]]; 
then 
  exit 0
fi

if which pbcopy >/dev/null;
then
  cat $TOOLKIT_PATH/$language/$selected | pbcopy 
  exit 0
else
  xclip -selection c $TOOLKIT_PATH/$language/$selected 
  exit 0 
fi
